export const COMPETITIONS = {
    FETCH: 'COMPETITIONS_FETCH',
    PENDING: 'COMPETITIONS_FETCH_PENDING',
    FULFILLED: 'COMPETITIONS_FETCH_FULFILLED',
}

export const DRAWER = {
    TOGGLE: 'DRAWER_TOGGLE'
}
